### ISSUE TITLE
Support for sourceRoot in options

### ISSUE THREAD

**Issue by djlimbs** [squarewolf/gulp-neuter#10]
Hello!

Due to my build process, I wasn't able to get source maps to find the original files by only using baseUrl and the output path parameters alone. So I modified the index.js code to support passing in "sourceRoot" as an option and was able to find the maps' original files. I'd like to submit a pull request if possible. Do you guys have a procedure for that, or should I just clone, branch then submit? Would it be easier just to communicate the added lines since it's a fairly small change? Thanks!

**Comment by tvervest** [comment]
Hey there!

Good to hear you're using the plugin to a point where you have a new feature request! And it sounds like a great feature to add :+1:

I (there's only one of "us" :grin: ) usually stick to doing a fork with a pull request. This way you'll be listed in github as a contributor, it's easy for me to check out the changes, and we'll be able to close this issue when closing the PR. If you can set up a pull request I'll look at it in the course of the week and we'll release a new update a.s.a.p. so that you kan keep using the regular npm version.

**Comment by djlimbs** [comment]
Great, will do! Thanks!

**Comment by tvervest** [comment]
Awesome, thanks! I've merged in #11 and added the new option to the documentation in the README file. I'll publish v0.2.1 in a second. Thanks for the feature :)
